language: ruby
install:
  - ./rebund/run download
  - bundle install --path vendor/bundle
script: bundle exec rake site:deploy
after_script:
  - ./rebund/run upload
env:
  global:
    - GIT_NAME=lacti
    - GIT_EMAIL=lactrious@gmail.com
    - REBUND_ENDPOINT=http://lacti-keyfile.herokuapp.com
    - secure: "rpAp1Medn5ih0aGzhHI8E3Mr6HLEl78q2IPrc2Q8HHUlD32ZQerpU/XyzjvkciWrhd3VxfvtTvDq/oVwlDx0W5L33ag0ZgQ71PkzaNIg+HD6f245XohwBa8jo8t5Ak7gwu2hBd3SzUIewdw64Evy/utGlxSSPbmqA9Fqy+WYTJU="
